# Generated by Django 5.1.2 on 2024-12-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='obj_money',
            field=models.IntegerField(db_index=True, max_length=1000000000000, verbose_name='Сумма для цели'),
        ),
    ]
