# Generated by Django 5.1.2 on 2024-10-12 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(db_index=True, max_length=100, verbose_name='Название цели')),
                ('slug', models.SlugField()),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='avatar',
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(blank=True, default=0, max_length=1000000000000, verbose_name='Деньги')),
                ('text', models.TextField(blank=True, default='Пусто', verbose_name='Пожелания')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ник')),
                ('obj', models.ForeignKey(blank=True, default='Нет целей', on_delete=django.db.models.deletion.CASCADE, to='financeAPI.objective', verbose_name='Цели')),
            ],
        ),
    ]
