# Generated by Django 5.1.2 on 2025-01-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='spending',
            field=models.CharField(choices=[('ТР', 'Траспорт'), ('ТУ', 'Товары и услуги'), ('КР', 'Кафе и рестораны'), ('ТП', 'Тарифы и подписки'), ('ДК', 'Долги и кредиты'), ('ПР', 'Прочее')], default='ПР', max_length=2, verbose_name='Тип операции'),
        ),
    ]
