# Generated by Django 5.1.2 on 2024-10-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['id'], 'verbose_name': 'Цели', 'verbose_name_plural': 'Цели'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['time_create'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
