# Generated by Django 5.1.2 on 2024-11-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0002_alter_objective_options_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objective',
            options={'ordering': ['id'], 'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.AddField(
            model_name='profile',
            name='obj',
            field=models.ManyToManyField(blank=True, default=0, to='financeAPI.objective', verbose_name='Цели'),
        ),
    ]
