# Generated by Django 5.1.2 on 2024-12-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0002_alter_objective_obj_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='all_money',
            field=models.FloatField(blank=True, default=0, verbose_name='Баланс'),
        ),
    ]
