# Generated by Django 5.1.2 on 2024-10-16 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0002_objective_rename_photo_user_avatar_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='money',
        ),
        migrations.AddField(
            model_name='objective',
            name='obj_money',
            field=models.FloatField(default=0, max_length=1000000000000, verbose_name='Сумма для цели'),
        ),
        migrations.AddField(
            model_name='profile',
            name='all_money',
            field=models.FloatField(blank=True, default=0, max_length=1000000000000, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
