# Generated by Django 5.1.2 on 2025-01-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('financeAPI', '0002_alter_history_spending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='spending',
            field=models.CharField(choices=[('Транспорт', 'Транспорт'), ('Товары и услуги', 'Товары и услуги'), ('Кафе и рестораны', 'Кафе и рестораны'), ('Тарифы и подписки', 'Тарифы и подписки'), ('Долги и кредиты', 'Долги и кредиты'), ('Прочее', 'Прочее')], default='PR', verbose_name='Тип операции'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='financeapi_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
