# Generated by Django 5.1.2 on 2024-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0003_alter_profile_all_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objective',
            name='obj_money',
            field=models.IntegerField(db_index=True, verbose_name='Сумма для цели'),
        ),
    ]
