# Generated by Django 5.1.2 on 2024-11-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0003_alter_objective_options_profile_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='obj',
            field=models.ManyToManyField(blank=True, default=0, related_name='obj', to='financeAPI.objective', verbose_name='Цели'),
        ),
    ]
