# Generated by Django 5.1.2 on 2024-11-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0004_alter_profile_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='obj',
            new_name='objs',
        ),
    ]
