# Generated by Django 5.1.2 on 2024-10-19 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0004_alter_objective_obj_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
