# Generated by Django 5.1.2 on 2024-11-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeAPI', '0006_remove_profile_objs_profile_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='obj',
            field=models.ManyToManyField(blank=True, related_name='objs', to='financeAPI.objective', verbose_name='Цели'),
        ),
    ]
